"""Prompt for the sentiment verdict.

The verdict is generated by a SINGLE historical-precedent analyst: it weighs
how distinctive the news is versus cosine-nearest prior articles/insights and
decides buy / sell / hold for the ticker at publication. There is no analyst
fan-out and no separate synthesis step — one structured-output call produces
the Verdict.
"""

ARTICLE_BLOCK = """\
TICKER UNDER ANALYSIS: {ticker}
PUBLISHED (UTC): {published_utc}
HEADLINE: {title}

ARTICLE BODY:
\"\"\"
{content}
\"\"\"
"""

# Inserted (via {label_legend}) only when the precedent excerpts carry "[label]"
# classification tags - i.e. the distilled precedent-source modes. Omitted for
# the article/insights modes, whose excerpts have no tags, so the model is
# never shown a legend for tags it will not see.
LABEL_LEGEND = """\
A leading "[label]" on an insight is its classification tag; the split is about
CERTAINTY / CLOSURE, not topic:
- "evidance-event" = it definitively HAPPENED or was reported - a settled,
  quotable fact (reported earnings/guidance/margins, completed M&A, a signed deal
  with terms, a suit filed, a recall, layoffs, a regulatory ruling, a macro
  release, a disclosed position, a real price move on news). Bullish or bearish,
  but settled.
- "informative" = it was ANNOUNCED but isn't settled yet - real but soft/open/
  unverified (an MoU/LoI/proposed deal with no terms, a product launch, a funding
  round, a planned/future action, a self-reported milestone not independently
  confirmed). In motion, but terms/close/materiality unsettled.
("DROP"-labelled low-signal insights are excluded from the lists above.)
Weight settled evidance-event overlaps more heavily than soft informative ones.

"""

# The precedents block header is mode-aware: the retrieval strategy decides both
# WHAT the prior articles are and HOW they are ordered, and the verdict model must
# be told accurately — calling ticker-history's plain recency list "cosine-nearest
# similar articles" misdirects the distinctiveness judgement. render_verdict picks
# one of these by the article's `precedent_kind` ("{ticker}" is filled in).
PRECEDENT_HEADERS = {
    # cosine ANN over the whole corpus: article / insights / distilled / hybrid modes
    "similarity": (
        "SIMILAR PAST ARTICLES (cosine-nearest prior articles from the corpus, "
        "published earlier; most similar first)."
    ),
    # ticker-history: the ticker's OWN prior articles, newest first (no similarity)
    "ticker-recency": (
        "RECENT NEWS ON {ticker} ({ticker}'s own prior articles, newest first)."
    ),
    # ticker-relevant: the ticker's OWN prior articles, ranked by relevance to this story
    "ticker-relevance": (
        "RELATED PAST NEWS ON {ticker} ({ticker}'s own prior articles, most "
        "relevant to this story first)."
    ),
    # ticker-history-fallback: ticker's own prior articles, newest first, with the
    # most similar cross-name articles appended when its own history is thin.
    "ticker-recency-fallback": (
        "RECENT NEWS ON {ticker} ({ticker}'s own prior articles, newest first; "
        "the most similar articles from other names are appended when {ticker}'s "
        "own history is thin)."
    ),
    # ticker-blend: ticker's own prior articles, the most relevant to this story
    # first, then the most recent.
    "ticker-blend": (
        "PAST NEWS ON {ticker} ({ticker}'s own prior articles — the most relevant "
        "to this story first, then the most recent)."
    ),
}
DEFAULT_PRECEDENT_KIND = "similarity"

# Single prompt: historical-precedent framing + the buy/sell/hold decision.
SENTIMENT_VERDICT_PROMPT = ARTICLE_BLOCK + """
{own_insights}{precedents_header}
Each entry is one prior article; any indented "- " lines beneath it are the
specific insight excerpts from that article that overlap this news:
{precedents}

{label_legend}You are a quantitative analyst of historical precedent. First judge how
distinctive this news actually is versus the prior articles above: is it a recurring
news pattern for this name/sector (likely already understood and priced), or
genuinely new information? When this article's own insights are listed above,
treat the indented excerpts as the concrete points of overlap with them. If the
list is empty or weak, say so.

Then decide buy / sell / hold for {ticker} at the moment of publication, and give
a confidence in [0,1] proportional to how strong and distinctive the evidence is.
Cite the specific overlaps (or their absence) that drove your decision in the
reasoning. When the signal is weak or ambiguous, prefer hold unless the article
itself is decisively material.
"""


# Pre-verdict summarizer: a cheap model distills the raw (often long,
# multi-language, boilerplate-heavy) article body into a decision-relevant brief
# that REPLACES the body in the verdict prompt. Kept factual/neutral so it never
# leaks a recommendation into the downstream verdict.
ARTICLE_SUMMARY_PROMPT = """\
You are a financial news analyst preparing a noise-free brief for a buy / sell /
hold decision on {ticker} at the moment this article was published.

Distill the article below to ONLY what bears on {ticker}'s near-term stock
reaction. DISCARD boilerplate: legal / safe-harbor / forward-looking-statement
disclaimers, "About <company>" descriptions, media and investor contact details,
generic market-size / CAGR filler, and repeated marketing language.

Preserve and make explicit:
- The core event or catalyst — what concretely happened or was announced.
- Hard figures: revenue, guidance, deal size and terms, units, % growth, dates.
- {ticker}'s ROLE: is it the central subject, or only incidental (its chip is a
  component, it is one name in a list)? State this plainly.
- Whether the event is SETTLED (happened / reported) or SOFT (announced,
  proposed, planned, self-reported, no terms).
- Named competitors, customers or partners and the relationship.

Rules:
- Write in ENGLISH even when the article is in another language.
- Be factual and neutral. Do NOT give a recommendation or predict the price.
- 120 words maximum. Terse prose or bullet lines. No preamble.

TICKER: {ticker}
HEADLINE: {title}
PUBLISHED (UTC): {published_utc}

ARTICLE:
\"\"\"
{content}
\"\"\"
"""


def render_summary(article: dict) -> str:
    """Render the pre-verdict article-summary prompt (Langfuse copy if available,
    in-repo template otherwise)."""
    from ticker_news.shared.prompts import get_prompt, safe_format

    kwargs = {
        "ticker": article.get("ticker") or "?",
        "title": (article.get("title") or "").strip(),
        "published_utc": str(article.get("published_utc") or "unknown"),
        "content": article.get("content") or "",
    }
    template = get_prompt("summarize-article", ARTICLE_SUMMARY_PROMPT)
    return safe_format(template, ARTICLE_SUMMARY_PROMPT, **kwargs)


def render_article(article: dict) -> dict:
    """Common .format kwargs for the prompt."""
    return {
        "ticker": article.get("ticker") or "?",
        "published_utc": str(article.get("published_utc") or "unknown"),
        "title": (article.get("title") or "").strip(),
        "content": article.get("content") or "",
    }


def render_verdict(article: dict) -> str:
    """Render the historical-precedent verdict prompt, fetching the current
    version from Langfuse if available (falls back to the in-repo template when
    Langfuse is disabled or unavailable). Fetches per call; the Langfuse
    client-side TTL cache absorbs the overhead.
    """
    from ticker_news.shared.prompts import get_prompt, safe_format

    kwargs = render_article(article)
    precedents = article.get("precedents") or []
    kwargs["precedents"] = (
        "\n".join(f"- {p}" for p in precedents) if precedents else "(none found)"
    )
    # The target article's own insights render as a self-contained section
    # (header + bullets) when present, or empty so the prompt collapses to just
    # the precedents block in article-similarity mode.
    own = article.get("own_insights") or []
    kwargs["own_insights"] = (
        "THIS ARTICLE'S INSIGHTS (the news under analysis, distilled):\n"
        + "\n".join(f"- {o}" for o in own)
        + "\n\n"
        if own else ""
    )
    # Only show the [label] legend when the excerpts are actually tagged
    # (distilled modes set precedent_labelled); article/insights have no tags.
    kwargs["label_legend"] = LABEL_LEGEND if article.get("precedent_labelled") else ""
    # Mode-aware precedents header: describe how the prior articles were actually
    # selected/ordered (cosine vs ticker recency vs ticker relevance) so the model
    # judges distinctiveness against an accurate description of the list.
    kind = article.get("precedent_kind") or DEFAULT_PRECEDENT_KIND
    header = PRECEDENT_HEADERS.get(kind, PRECEDENT_HEADERS[DEFAULT_PRECEDENT_KIND])
    kwargs["precedents_header"] = header.format(ticker=kwargs["ticker"])
    template = get_prompt("sentiment-verdict", SENTIMENT_VERDICT_PROMPT)
    return safe_format(template, SENTIMENT_VERDICT_PROMPT, **kwargs)
